Reg/urls.py
from django.conf.urls import url
from . import views

app_name = 'registration'
urlpatterns = [
    url(r'^$', views.createuser, name='registration_page'),
]

TestWorkUsers/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5
"""TestWorkUsers URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('Reg.urls'), name='registration'),
    url(r'^(home/)?', include('home.urls'), name='home'),
    url(r'^login/', include('login.urls'), name='login'),
    url(r'^logout/', views.logout_f, name='logout'),
    url(r'^about/', include('about.urls'), name='about'),
]

about/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5
from django.conf.urls import url
from . import views

app_name = 'about'
urlpatterns = [
    url(r'^$', views.about_page, name='about_page'),
    url(r'^(?P<id>[0-9]+)/', views.about_id_page, name='profile'),
]

home/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5
"""TestWorkUsers URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
]

login/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url('^$', views.login, name='login_page')
]

Reg/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models


class People(models.Model):
    user_number = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday_date = models.DateField()
    about = models.CharField(max_length=255)

    def __unicode__(self):
        return self.user_number

about/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Reg/forms.py
from django.forms import ModelForm
from .models import People, User


class RegPeopleForm(ModelForm):
    class Meta:
        model = People
        fields = ['birthday_date', 'about']


class RegUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name']

login/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from django.forms import ModelForm, Form
from Reg.models import User
from django import forms
from django.contrib.auth import authenticate

class LoginUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class LoginForm(Form):
    username = forms.CharField(label=u'Имя пользователя')
    password = forms.CharField(label=u'Пароль', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        if not self.errors:
            user = authenticate(username=cleaned_data['username'], password=cleaned_data['password'])
            if user is None:
                raise forms.ValidationError(u'Логин не найден')
            self.user = user
        return cleaned_data

    def get_user(self):
        return self.user or None

Reg/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import RegPeopleForm, RegUserForm


def createuser(request):
    if request.method == "POST":
        uform = RegUserForm(data=request.POST)
        pform = RegPeopleForm(data=request.POST)
        if uform.is_valid() and pform.is_valid():
            user = uform.save()
            people = pform.save(commit=False)
            people = user
            people.save()
        return HttpResponseRedirect('/')
    else:
        uform=RegUserForm()
        pform=RegPeopleForm()
        return render(request, 'registration/registration.html', {'uform': uform, 'pform': pform})

TestWorkUsers/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from django.contrib.auth import logout
from django.http import HttpResponseRedirect

def logout_f(request):
    logout(request)
    return HttpResponseRedirect('/')

about/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from Reg.models import People #AbstrUser,
from django.shortcuts import render, get_object_or_404

def about_page(request):
    all_users = People.objects.all()
    output = ', '.join([q.people_first_name for q in all_users]).encode('utf-8')
    context = {'output': output}
    return render(request, 'about/about.html', context)

def about_id_page(request, **id):
    user_id = ''.join(id.values()).encode('ASCII')
    output = get_object_or_404(People, pk=user_id)
    context = {'output': output}
    if user_id:
        return render(request, 'about/about_id.html', context)

home/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from django.shortcuts import render

def home_page(request, page, **id):
    if request.user.is_authenticated():
        user = request.user
        return render(request, 'home/home.html', {'user': user})
    else:
        return render(request, 'home/home.html', {})

login/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3.5

from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginUserForm, LoginForm
#from django.shortcuts import redirect
from django.http import HttpResponseRedirect


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            if form.get_user():
                login(request, form.get_user())
                return HttpResponseRedirect('/')
    else:
        form = LoginForm()
    return render(request, 'login/login.html', {'form': form})


    # if ('username' in request.GET) and ('password' in request.GET):
    #     username = request.GET['username']
    #     password = request.GET['password']
    #     user = authenticate(username=username, password=password)
    #     if user is not None:
    #         login(user=user)
    #         return HttpResponseRedirect('/')
    #     else:
    #         form = LoginUserForm()
    #         message = 'Пользователь не найден'
    #         return render(request, 'login/login.html', {'form': form, 'message': message})
    # else:
    #     form = LoginUserForm()
    #     return render(request, 'login/login.html', {'form': form})

templates/about/about.html
{% extends "base.html" %}
{% block title %}
Все анкеты пользователей
{% endblock %}
{% block body %}
{% for i in context.choice_ %}
<p><a href="{% url 'about:about_page {{i.id}}' %}">{{i.first_name}}{{i.last_name}}</a></p>
{% empty %}
<p>Анкеты не найдены</p>
{% endfor %}
{% endblock %}

templates/about/about_id.html
{% extends "base.html" %}
{% block title %}
Анкета {{user_id}}
{% endblock %}
{% block body %}
{{context}}
{% endblock %}

templates/base.html
{% load staticfiles %}
{% block page %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body {
            background: {% static 'imgs/abstract-940049.jpg' %} 100% 100% no-repeat;
            background-size: cover;
        }
    </style>
</head>
<body background="{% static 'imgs/abstract-940049.jpg' %}">
<table class="logo" width="100%" border="0">
    <tr>
        <td width="20%"><a href="{% url 'home:home_page' %}"><img src="{% static 'imgs/python3.png' %}" alt="Logo"></a></td>
        <td width="80%">
            <table width="100%" border="0">
                {% if user.is_authenticated %}
                <tr>
                    <td width="33%" align="left">
                        <a href="{% url 'about:about_page' %}">Все анкеты</a>
                    </td>
                    <td width="33%" align="center">
                        <a href="{% url 'about:profile' user.pk %}">Личный кабинет</a>
                    </td>
                    <td width="34%" align="right">
                            {% csrf_token %}
                            <a href="{% url 'logout' %}">Выход</a>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td width="50%">
                        <a href="{% url 'registration:registration_page' %}" >Регистрация</a>
                    </td>
                    <td width="50%">
                        <a href="{% url 'login:login_page' %}" >Вход </a>
                    </td>
                </tr>
                {% endif %}
            </table>
        </td>
    </tr>
</table>
{% block body %}{% endblock %}
</body>
</html>
{% endblock %}

templates/home/home.html
{% extends "base.html" %}
{% block title %}
Главная
{% endblock %}
{% block body %}
<p>Добро пожаловать!</p>
{% if user.is_autenticated %}
<p>Вы можете просматривать профили</p>
{% else %}
<p>Для просмотра профилей войдите в аккаунт</p>
{% endif %}
{% endblock %}

templates/login/login.html
{% extends "base.html" %}
{% block title %}
Вход на сайт
{% endblock %}
{% block body %}
{% if message %} {{message}} {% endif %}
<form name="login_form" method="post" action="{% url 'home:home_page' as var %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Вход" />
</form>
{% endblock %}